version: "3"

services:
  app:
    image: golang:1.22.1-alpine
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - ${APP_FOWERD_PORT:-80}:${APP_PORT:-80}
    command: go run .
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    env_file:
      - .env
    ports:
      - ${DB_FOWERD_PORT:-3306}:3306
    healthcheck:   # here
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 3s
      retries: 12
      start_period: 5s