version: "3"

services:
  app:
    image: golang:1.22.1-alpine
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - ${APP_FOWERD_PORT:-80}:${APP_PORT:-80}
    command: go run .
